In [ ]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer as Tfidf, CountVectorizer as Cvec
from sklearn.model_selection import train_test_split as TTS
from sklearn.naive_bayes import MultinomialNB as MNB
from sklearn.svm import SVC
from wordcloud import WordCloud
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/JHub/Module 5/spam.csv", encoding = "ISO-8859-1")
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [ ]:
df.drop(columns=["Unnamed: 2","Unnamed: 3", "Unnamed: 4"], inplace=True)

In [ ]:
#designate features and 
Y = df['v1']
X = df['v2']

In [ ]:
#Generate encoding objects for TFIDF and Count vectoriser and classifer objects

encs = [Tfidf(), Cvec(decode_error="ignore")]
models = [SVC(), MNB()]

for model in models:
  for enc in encs:
    #split data
    X_train, X_test, Y_train, Y_test = TTS(X, Y, test_size=0.33, random_state=1)

    #encode data
    obj = enc
    X_train = obj.fit_transform(X_train)

    #train model
    mod = model
    mod.fit(X_train, Y_train)

    #test model
    X_test = obj.transform(X_test)
    Y_predict = mod.predict(X_test)

    #Metrics
    cm = confusion_matrix(Y_test, Y_predict)
    ascore = accuracy_score(Y_test, Y_predict)

    #Output:
    print(model, enc, ascore)

SVC() TfidfVectorizer() 0.9798803697661773
SVC() CountVectorizer(decode_error='ignore') 0.9771615008156607
MultinomialNB() TfidfVectorizer() 0.958673191952148
MultinomialNB() CountVectorizer(decode_error='ignore') 0.9809679173463839

train score: 0.970265202250201
test score: 0.958673191952148